name: Create Release
on:
  workflow_dispatch: {}
jobs:
  test:
    needs: semantic-release
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - uses: actions/checkout@v2
      - run: make build

  binary:
    needs: semantic-release
    runs-on: ubuntu-latest
    env:
      VERSION: v${{ needs.semantic-release.outputs.release-version }}
    container:
      image: golang:1.22
    steps:
      - uses: actions/checkout@v2
      - run: make release
      - name: Upload binaries to release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ needs.semantic-release.outputs.release-version }}
          gzip: false
          allow_override: true
          files: >
            ./.bin/gitlab-multirepo-deployer
            ./.bin/gitlab-multirepo-deployer_darwin-amd64
            ./.bin/gitlab-multirepo-deployer_linux-amd64

  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.semantic.outputs.release-version }}
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
    steps:
      - uses: actions/checkout@v2
      - uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}